# Generated by Django 3.2 on 2022-02-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task_item',
            new_name='Item',
        ),
    ]
