# Generated by Django 3.2 on 2022-02-08 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_rename_task_item_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='due_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 8, 14, 19, 37, 235818, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
